 name: discord-webhook
  # You may pin to the exact commit or the version.
  # uses: johnnyhuy/actions-discord-git-webhook@ba54912b26910da886c9095317d6da6182a87224
  uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
  with:
    webhook_url: "https://discord.com/api/webhooks/1126943728272166994/vzlEIhxrBL8FR3xgVMc8dXIPW87IlYh5Tl_YXlBktSp9Ff2s-eisyoCWOfBY0VREFBNG"
